#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Pomocalc\Command\CalculatePomodorosCommand;
use Symfony\Component\Console\Application;

$app = new Application('Pomocalc', '0.1.x-dev');

$app->add(new CalculatePomodorosCommand());

$app->run();